// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKe9Ygf67vMlzWMdyPztZ4891Kga-kafs',
    appId: '1:691827108352:web:cf01f42e01ff93903b06e5',
    messagingSenderId: '691827108352',
    projectId: 'travel-planner-c7311',
    authDomain: 'travel-planner-c7311.firebaseapp.com',
    storageBucket: 'travel-planner-c7311.firebasestorage.app',
    measurementId: 'G-C17BH2D4W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2TKOVlhiXjCiB3FJDRGsSPrFXN231RQ8',
    appId: '1:691827108352:android:79674cd2611640e93b06e5',
    messagingSenderId: '691827108352',
    projectId: 'travel-planner-c7311',
    storageBucket: 'travel-planner-c7311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSEPsjRuaSDvAPztbR-ebw1yCUT0KHxsI',
    appId: '1:691827108352:ios:3c74583cf337fe373b06e5',
    messagingSenderId: '691827108352',
    projectId: 'travel-planner-c7311',
    storageBucket: 'travel-planner-c7311.firebasestorage.app',
    iosBundleId: 'com.example.travelPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSEPsjRuaSDvAPztbR-ebw1yCUT0KHxsI',
    appId: '1:691827108352:ios:3c74583cf337fe373b06e5',
    messagingSenderId: '691827108352',
    projectId: 'travel-planner-c7311',
    storageBucket: 'travel-planner-c7311.firebasestorage.app',
    iosBundleId: 'com.example.travelPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKe9Ygf67vMlzWMdyPztZ4891Kga-kafs',
    appId: '1:691827108352:web:a107069a679be0c63b06e5',
    messagingSenderId: '691827108352',
    projectId: 'travel-planner-c7311',
    authDomain: 'travel-planner-c7311.firebaseapp.com',
    storageBucket: 'travel-planner-c7311.firebasestorage.app',
    measurementId: 'G-PC9PZL6F29',
  );
}
